---


- name: install nginx
  apt: name=nginx state=present

- name: open ports 
  ufw: rule=allow port={{item}}
  with_items:
  - 80
  - 443
  notify:
  - restart ufw        

- name: create nginx config files
  template: src=nginx.j2 dest=/etc/nginx/nginx.conf
- name: create new root directory
  file: path=/var/www/html/{{ website }} state=directory
- name: create website default index
  template: src=index.j2 dest=/var/www/html/{{ website }}/index.html
- name: create virtual hosts
  template: src=host.j2 dest=/etc/nginx/sites-enabled/{{ website }}
  notify:
  - restart nginx    

