---
- hosts: test
  vars_prompt:
  -  name: website
     prompt: " please enter your website name ? "
     private: no
  -  name: mysql_passwd
     prompt: " please enter your Mysql root password ? "
  roles:
     - ready
     - nginx
     - mysql
     - node.js
     - ghost 

